steps:
  # Paso 1: Construir la imagen del contenedor usando el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smaiflow-predict-your-greatness:$COMMIT_SHA'
      - '.'

  # Paso 2: Subir la imagen construida a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smaiflow-predict-your-greatness:$COMMIT_SHA'

  # --- PASO FINAL Y CRUCIAL AÑADIDO ---
  # Paso 3: Desplegar la nueva imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smaiflow-predict-your-greatness' # El nombre de tu servicio
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smaiflow-predict-your-greatness:$COMMIT_SHA' # La imagen que acabamos de subir
      - '--region'
      - 'us-west1' # La región de tu servicio
      - '--quiet' # Para que no pida confirmación

# Opciones de configuración que ya teníamos
options:
  logging: CLOUD_LOGGING_ONLY